24_AspNetWebHelpers/Controllers/AntiForgeryController.cs
using _24_AspNetWebHelpers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _24_AspNetWebHelpers.Controllers
{
    public class AntiForgeryController : Controller
    {
        
        public ActionResult Test()
        {
            return View(Veritabani.veriler);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]  //olusturalan kodun kontrolunu saglariz.eslesme dogru olursa post olur.
        public ActionResult Test(int id)
        {
            Veritabani.veriler.RemoveAt(id);
            return RedirectToAction("Test");
        }

        public ActionResult FakeTest()
        {
            return View();
        }
    }
}

24_AspNetWebHelpers/Views/AntiForgery/FakeTest.cshtml
@{
    ViewBag.Title = "FakeTest";
}

<h2>FakeTest</h2>

<div class="row">
    @using (Html.BeginForm("Test","AntiForgery",FormMethod.Post))
    {
        <strong>index :</strong>
        @Html.TextBox("id", "", new { @class = "form-control" })

        <button class="btn btn-danger" type="submit">Sil</button>

    }
</div>

24_AspNetWebHelpers/Views/AntiForgery/Test.cshtml
@model List<string>
@{
    ViewBag.Title = "Test";
}

<h2>Anti Forgery Token</h2>
<hr />
<div class="row">
    <ul class="list-group">
        @foreach (string item in Model)
        {
            <li class="list-group-item">@item</li>
        }
    </ul>
</div>
<hr />

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken() //anahtar olusturduk
        <strong>index :</strong>
        @Html.TextBox("id","",new {@class="form-control" })
        
        <button class="btn btn-danger" type="submit">Sil</button>

    }
</div>